name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "what a wonderful world"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            vinayak868/gitops01:${{ github.sha }}
            ghcr.io/vinatu/reactapp:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vinatu/gitops-infra
          ref: 'master'
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup git config
        run: |
          git config --global user.email "l00179000@atu.ie"
          git config --global user.name "vinatu"
          sed -i "s#vinayak868/gitops01:.*#vinayak868/gitops01:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image tag to ${{ github.sha }}"
      - run: git push origin master
